### ISSUE TITLE
Inconsistent exploding behaviour within clusters and more

### ISSUE THREAD

**Issue by aytunch** [lpongetti/flutter_map_marker_cluster#123]
The two clusters you see in the video each have 2 `Marker`s at same lat long.
When I press the top left cluster, it centers and then "explodes"
But when I press the bottom right cluster, it just centers. For it to show the contents, I need to press one more time.

Sorry that this issue turned out to be an issue cluster. pun intended :D I think it can help other users too.

I have a couple of questions:

1. How can I make it such that users don't need to press it a second time to see the singular markers? (just like top left cluster)
2. How can I un-explode the singular markers back to the cluster state, once the user presses on an empty space in the map. I see there is a similar API for `popUpController.hideAll` but I guess popups are something different than the markers. I handle the onPressed of the markers within the widgets.
3. When we explode the cluster, cluster icon's opacity is decreased and stays at the same place. When user presses it, we un-explode the cluster back. How can we customize the appearance of the exploded state of the cluster widget? let's say I want to put there a more explanatory icon like "close - X".
4. Is there a way to catch cluster `onPressed` events and decide if we want to explode and unexplode markers? Let's say maybe I want to keep the contents of several clusters in an expanded state.
5. Before using this plugin, I was able to animate the show/hide states of markers in the `MarkerLayerOptions.markers`. Now that I carried those markers under `MarkerClusterLayerOptions.markers`, the `AnimatedOpacity` don't work anymore. I guess there is a problem with the state object somewhere. (I don't use `children` property. instead put all my markers under `layers`)

https://user-images.githubusercontent.com/6442915/177625477-90bed625-ab06-4180-b782-512cdb0bab2e.mov

On another note, you can see that the exploded cluster disappears from the right edge of the screen. I was struggling with this issue on the parent `flutter_map` and have an open PR https://github.com/fleaflet/flutter_map/pull/1291
I was using my own branch but unfortunately I am forced to use the main flutter_map along with this cluster plugin (even if I branched out of flutter_map: ^1.1.1)

- Is there a way to use and test out cluster plugin with my branch without pub get dependency errors?
- And would my PR fix disappearing clusters and help out this plugin somehow? In the code I could not see where the Rect size was set for the spider rect.

https://user-images.githubusercontent.com/6442915/177626183-f31fef1b-113d-4fb8-a8ac-8491ade4f047.mov

**Comment by aytunch** [comment]
@lpongetti this issue is still present in our app.

**Comment by lpongetti** [comment]
can you pls prepare a sample code to do some tests?

**Comment by lpongetti** [comment]
fixed with version 0.5.4

**Comment by lpongetti** [comment]
fixed with version 0.5.4

**Comment by aytunch** [comment]
@lpongetti thanks. I will try it as soon as 0.5.4 is live on pub dev. I still see 0.5.3

**Comment by lpongetti** [comment]
yes, one moment.. now my connection is very poor :)

**Comment by aytunch** [comment]
Works perfect and as intended. Thanks @lpongetti

**Comment by basnetjiten** [comment]
@aytunch How did you resolved the issues of on click cluster it first centers and need to click it second time to show the clusters. Could you please elaborate a bit.
